#!/usr/bin/env python

env = SConscript("../../extern/godot-cpp/SConstruct", {"api_version": "4.7"})

env.Append(CPPPATH=["."])
sources = Glob("*.cpp")

library = env.SharedLibrary(
    "../../game/bin/libswarm{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

env.NoCache(library)
Default(library)
